<!DOCTYPE html>
<html lang="hu">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>GamerZone</title>
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      background-color: #121212;
      color: #fff;
    }

    header {
      background-color: #1f1f1f;
      padding: 1rem 2rem;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    header h1 {
      margin: 0;
      font-size: 1.8rem;
      color: #00ffc8;
    }

    nav a {
      margin-left: 1.5rem;
      text-decoration: none;
      color: #ccc;
      transition: color 0.2s ease-in-out;
    }

    nav a:hover {
      color: #00ffc8;
    }

    .hero {
      text-align: center;
      padding: 4rem 2rem;
      background-image: url('https://cdn.pixabay.com/photo/2017/01/31/21/23/controller-2023445_1280.png');
      background-repeat: no-repeat;
      background-position: center;
      background-size: contain;
    }

    .hero h2 {
      font-size: 2.5rem;
      margin-bottom: 1rem;
    }

    .hero p {
      max-width: 600px;
      margin: 0 auto 2rem auto;
      font-size: 1.2rem;
      color: #aaa;
    }

    .hero button {
      background-color: #00ffc8;
      border: none;
      padding: 1rem 2rem;
      font-size: 1rem;
      cursor: pointer;
      border-radius: 8px;
      transition: background-color 0.3s ease;
    }

    .hero button:hover {
      background-color: #00c0a1;
    }

    footer {
      text-align: center;
      padding: 1rem;
      background-color: #1f1f1f;
      color: #888;
    }
  </style>
</head>
<body>

  <header>
    <h1>PlayerZone</h1>
    <nav>
      <a href="#">Kezdőlap</a>
      <a href="https://mega.nz/file/NS1FhJpR#IlSKHqovy7WXusX7uocKrTwKpCeCQgaEWJX67B2wv3Y">Játékok</a>
      <a href="#">Letöltés</a>
      <a href="#">Kapcsolat</a>
    </nav>
  </header>

  <section class="hero">
  <h2>Fedezd fel a végső kalandot!</h2>
  <p>Csatlakozz több ezer játékoshoz egy epikus fantasy világban, ahol a képességeid számítanak!</p>
 <img src="https://cdna.artstation.com/p/assets/images/images/079/033/774/large/rob-kesz.jpg?1723763177.jpg" alt="Játék képe" class="hero-image" />
  <button><a href="https://mega.nz/file/NS1FhJpR#IlSKHqovy7WXusX7uocKrTwKpCeCQgaEWJX67B2wv3Y" class="button-link">Játék indítása</a></button>
</section>

  <footer>
    &copy; 2025 GamerZone. Minden jog fenntartva.
  </footer>

</body>
</html>
